scp -r -P 18765 /Volumes/DEV/SITES/muttagency.com/public/build devbyjcs@es32.siteground.eu:~/public_html/mutt/public
scp -r -P 18765 /Volumes/DEV/SITES/muttagency.com/public/img devbyjcs@es32.siteground.eu:~/public_html/mutt/public
scp -r -P 18765 /Volumes/DEV/SITES/muttagency.com/public/svg devbyjcs@es32.siteground.eu:~/public_html/mutt/public
scp -r -P 18765 /Volumes/DEV/SITES/muttagency.com/resources/lang/fr devbyjcs@es32.siteground.eu:~/public_html/mutt/resources/lang
scp -r -P 18765 /Volumes/DEV/SITES/muttagency.com/resources/views devbyjcs@es32.siteground.eu:~/public_html/mutt/resources
scp -r -P 18765 /Volumes/DEV/SITES/muttagency.com/app/Http devbyjcs@es32.siteground.eu:~/public_html/mutt/app
#scp -r -P 18765 /Volumes/DEV/SITES/muttagency.com/app/Mail devbyjcs@es32.siteground.eu:~/public_html/mutt/app
scp -r -P 18765 /Volumes/DEV/SITES/muttagency.com/routes devbyjcs@es32.siteground.eu:~/public_html/mutt
#scp -r -P 18765 /Volumes/DEV/SITES/muttagency.com/admin devbyjcs@es32.siteground.eu:~/public_html/mutt
#scp -r -P 18765 /Volumes/DEV/SITES/muttagency.com/vendor devbyjcs@es32.siteground.eu:~/public_html/mutt